require:
  - rubocop-packaging

AllCops:
  TargetRubyVersion: 2.5
  DisabledByDefault: true

Packaging/BundlerSetupInTests:
  Enabled: true

Packaging/GemspecGit:
  Enabled: true

Packaging/RequireHardcodingLib:
  Enabled: true

Packaging/RequireRelativeHardcodingLib:
  Enabled: true
